# Wallpaper
preload = /home/tyler/Pictures/wallpaper/wp28.jpg 
wallpaper = LVDS-2,/home/tyler/Pictures/wallpaper/wp28.jpg
wallpaper = LVDS-1,/home/tyler/Pictures/wallpaper/wp28.jpg
wallpaper_mode = fit

