# Wallpaper
preload = /home/tyler/Saved/To_Install/Wallpaper/907468.jpg
wallpaper = LVDS-2,/home/tyler/Saved/To_Install/Wallpaper/907468.jpg
wallpaper = LVDS-1,/home/tyler/Saved/To_Install/Wallpaper/907468.jpg
wallpaper_mode = fit

